name: Struts
fullname: Apache Struts
subdomain: struts
bg_color: '#3186c3'
fg_color: '#3f70b6'
project_url: https://struts.apache.org
description: |
  Apache Struts is an MVC web application framework in Java
git_commit_url_prefix: https://github.com/apache/struts/commit/
github_search_url_prefix: https://github.com/apache/struts/search?utf8=✓&q=
github_edit_cve_url_prefix: https://github.com/VulnerabilityHistoryProject/struts-vulnerabilities/edit/dev/cves/
vulnerabilities_description: |
  These vulnerabilities are reported by the development team [on their website](https://cwiki.apache.org/confluence/display/WW/Security+Bulletins)
developers_description: |
  The following is a list of developers who are involved in code that was found to be vulnerable. Specifically, developers end up here if they were the author of a commit to code that was, at some point in time, fixed for a vulnerability. Note that this is NOT a comprehensive list.
test_filepath:
  - test

# A file name that ends with this string is considered to be source code
# The way I found these was to do this at the root of the git repo
#
# find -type f | cut -c 3- | sed 's/.*\.//' | sort | uniq > ~/struts_exts.txt
#
# Then filtered by hand. Remove anything compressed, binary, dev-tools, etc.
source_code_extensions:
  - .cfg
  - .cmd
  - .css
  - .dtd
  - .eot
  - .ftl
  - .gdsl
  - .html
  - .idx
  - .java
  - Jenkinsfile
  - .jjt
  - .jrxml
  - .js
  - .jsp
  - .map
  - .md
  - .mvnw
  - .pack
  - .properties
  - .sample
  - .svg
  - .tld
  - .ttf
  - .txt
  - .vm
  - .woff
  - .woff2
  - .xml
  - .xsl
  - .yaml
  - .yml
